#
# Module manifest for root module 'PsCompletions'
#
# Generated by: Ralf Rastlos <vollsynthetik@gmail.com>
#
# Generated on: 07/28/2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PsCompletions.psm1'

    # Version number of this module.
    ModuleVersion          = '0.1.0'
    
    # Supported PSEditions
    CompatiblePSEditions   = @(
        'Core'
    )
    
    # ID used to uniquely identify this module
    GUID                   = '327a64d7-6ff4-4621-ac6f-2d9598910c22'
    
    # Author of this module
    Author                 = 'vollsynthetik@gmail.com'
    
    # Company or vendor of this module
    CompanyName            = 'Darkstar GmbH'
    
    # Copyright statement for this module
    Copyright              = '(c) Darkstar GmbH. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description            = 'Provides extensible completion functionality for the powershell'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '7.0'
    
    # Name of the PowerShell host required by this module
    PowerShellHostName     = ''
    
    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion  = '2.0'
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '7.0'
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    CLRVersion             = '5.0'
    
    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture  = 'None'
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules        = @(
        'TabExpansionPlusPlus'
    )
    
    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = @(
        'System.Management.Automation',
        'Microsoft.Management.Infrastructure'
    )
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess       = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess         = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess       = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules          = @(
        'completions/CimCompletions/CimCompletions',
        'completions/WsManCompletions/WsManCompletions'
    )
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = @()
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport        = @()
    
    # Variables to export from this module
    VariablesToExport      = '*'
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = @()
    
    # DSC resources to export from this module
    DscResourcesToExport   = @()
    
    # List of all modules packaged with this module
    ModuleList             = @(
    )
    
    # List of all files packaged with this module
    FileList               = @(
        'PsCompletions.psm1'
    )
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                       = @("completionmodule"; "cim"; "cimcmdlets"; "cimcompletions"; "completions"; "tabexpansionplusplus"; "tabexpansion++")
    
            # A URL to the license for this module.
            LicenseUri                 = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
    
            # A URL to the main website for this project.
            ProjectUri                 = 'https://github.com/Darkstar-GmbH/ps-completions/'
    
            # A URL to an icon representing this module.
            IconUri                    = ''
    
            # ReleaseNotes of this module
            ReleaseNotes               = 'CHANGELOG.md'
    
            # Prerelease string of this module
            Prerelease                 = ''
    
            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance   = $true
    
            # External dependent modules of this module
            ExternalModuleDependencies = @(
                "TabExpansionPlusPlus"
            )
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = ''
    
    }